name: Build Mod
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        java: [17]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # อัปเกรดเป็น v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4 # อัปเกรดเป็น v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Make Gradle Wrapper Executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # แก้ไขถูกต้องแล้ว
        with:
          name: RenderReducer-Mod
          path: build/libs/*.jar
